version: '3.1'

services:

  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: coding-interview
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:localhost@mongo:27017/